services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    user: ${PUID}:${PGID}
    ports:
      - "8080:80"
    volumes:
      - /data:/srv
      - ./database.db:/database.db
      - ./settings.json:/.filebrowser.json
