version: '3.8'

services:
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - heimdall_config:/config
    ports:
      - ${HEIMDALL_PORT}:80       
    restart: unless-stopped

volumes:
  heimdall_config:
    driver: local
